// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/MetadataModel.proto

package com.cloudata;

public final class MetadataModel {
  private MetadataModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TypeMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional .google.protobuf.DescriptorProto type_descriptor = 3;
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    boolean hasTypeDescriptor();
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    com.google.protobuf.DescriptorProtos.DescriptorProto getTypeDescriptor();
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder getTypeDescriptorOrBuilder();
  }
  /**
   * Protobuf type {@code TypeMetadata}
   */
  public static final class TypeMetadata extends
      com.google.protobuf.GeneratedMessage
      implements TypeMetadataOrBuilder {
    // Use TypeMetadata.newBuilder() to construct.
    private TypeMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TypeMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TypeMetadata defaultInstance;
    public static TypeMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public TypeMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TypeMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.DescriptorProtos.DescriptorProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = typeDescriptor_.toBuilder();
              }
              typeDescriptor_ = input.readMessage(com.google.protobuf.DescriptorProtos.DescriptorProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(typeDescriptor_);
                typeDescriptor_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.MetadataModel.internal_static_TypeMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.MetadataModel.internal_static_TypeMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.MetadataModel.TypeMetadata.class, com.cloudata.MetadataModel.TypeMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<TypeMetadata> PARSER =
        new com.google.protobuf.AbstractParser<TypeMetadata>() {
      public TypeMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TypeMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .google.protobuf.DescriptorProto type_descriptor = 3;
    public static final int TYPE_DESCRIPTOR_FIELD_NUMBER = 3;
    private com.google.protobuf.DescriptorProtos.DescriptorProto typeDescriptor_;
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    public boolean hasTypeDescriptor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    public com.google.protobuf.DescriptorProtos.DescriptorProto getTypeDescriptor() {
      return typeDescriptor_;
    }
    /**
     * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
     */
    public com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder getTypeDescriptorOrBuilder() {
      return typeDescriptor_;
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      typeDescriptor_ = com.google.protobuf.DescriptorProtos.DescriptorProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasTypeDescriptor()) {
        if (!getTypeDescriptor().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, typeDescriptor_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, typeDescriptor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.MetadataModel.TypeMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.MetadataModel.TypeMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TypeMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.MetadataModel.TypeMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.MetadataModel.internal_static_TypeMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.MetadataModel.internal_static_TypeMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.MetadataModel.TypeMetadata.class, com.cloudata.MetadataModel.TypeMetadata.Builder.class);
      }

      // Construct using com.cloudata.MetadataModel.TypeMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTypeDescriptorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (typeDescriptorBuilder_ == null) {
          typeDescriptor_ = com.google.protobuf.DescriptorProtos.DescriptorProto.getDefaultInstance();
        } else {
          typeDescriptorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.MetadataModel.internal_static_TypeMetadata_descriptor;
      }

      public com.cloudata.MetadataModel.TypeMetadata getDefaultInstanceForType() {
        return com.cloudata.MetadataModel.TypeMetadata.getDefaultInstance();
      }

      public com.cloudata.MetadataModel.TypeMetadata build() {
        com.cloudata.MetadataModel.TypeMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.MetadataModel.TypeMetadata buildPartial() {
        com.cloudata.MetadataModel.TypeMetadata result = new com.cloudata.MetadataModel.TypeMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (typeDescriptorBuilder_ == null) {
          result.typeDescriptor_ = typeDescriptor_;
        } else {
          result.typeDescriptor_ = typeDescriptorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.MetadataModel.TypeMetadata) {
          return mergeFrom((com.cloudata.MetadataModel.TypeMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.MetadataModel.TypeMetadata other) {
        if (other == com.cloudata.MetadataModel.TypeMetadata.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTypeDescriptor()) {
          mergeTypeDescriptor(other.getTypeDescriptor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasTypeDescriptor()) {
          if (!getTypeDescriptor().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.MetadataModel.TypeMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.MetadataModel.TypeMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional .google.protobuf.DescriptorProto type_descriptor = 3;
      private com.google.protobuf.DescriptorProtos.DescriptorProto typeDescriptor_ = com.google.protobuf.DescriptorProtos.DescriptorProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.DescriptorProtos.DescriptorProto, com.google.protobuf.DescriptorProtos.DescriptorProto.Builder, com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder> typeDescriptorBuilder_;
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public boolean hasTypeDescriptor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.DescriptorProto getTypeDescriptor() {
        if (typeDescriptorBuilder_ == null) {
          return typeDescriptor_;
        } else {
          return typeDescriptorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public Builder setTypeDescriptor(com.google.protobuf.DescriptorProtos.DescriptorProto value) {
        if (typeDescriptorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          typeDescriptor_ = value;
          onChanged();
        } else {
          typeDescriptorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public Builder setTypeDescriptor(
          com.google.protobuf.DescriptorProtos.DescriptorProto.Builder builderForValue) {
        if (typeDescriptorBuilder_ == null) {
          typeDescriptor_ = builderForValue.build();
          onChanged();
        } else {
          typeDescriptorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public Builder mergeTypeDescriptor(com.google.protobuf.DescriptorProtos.DescriptorProto value) {
        if (typeDescriptorBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              typeDescriptor_ != com.google.protobuf.DescriptorProtos.DescriptorProto.getDefaultInstance()) {
            typeDescriptor_ =
              com.google.protobuf.DescriptorProtos.DescriptorProto.newBuilder(typeDescriptor_).mergeFrom(value).buildPartial();
          } else {
            typeDescriptor_ = value;
          }
          onChanged();
        } else {
          typeDescriptorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public Builder clearTypeDescriptor() {
        if (typeDescriptorBuilder_ == null) {
          typeDescriptor_ = com.google.protobuf.DescriptorProtos.DescriptorProto.getDefaultInstance();
          onChanged();
        } else {
          typeDescriptorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.DescriptorProto.Builder getTypeDescriptorBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTypeDescriptorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder getTypeDescriptorOrBuilder() {
        if (typeDescriptorBuilder_ != null) {
          return typeDescriptorBuilder_.getMessageOrBuilder();
        } else {
          return typeDescriptor_;
        }
      }
      /**
       * <code>optional .google.protobuf.DescriptorProto type_descriptor = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.DescriptorProtos.DescriptorProto, com.google.protobuf.DescriptorProtos.DescriptorProto.Builder, com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder> 
          getTypeDescriptorFieldBuilder() {
        if (typeDescriptorBuilder_ == null) {
          typeDescriptorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.DescriptorProtos.DescriptorProto, com.google.protobuf.DescriptorProtos.DescriptorProto.Builder, com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder>(
                  typeDescriptor_,
                  getParentForChildren(),
                  isClean());
          typeDescriptor_ = null;
        }
        return typeDescriptorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TypeMetadata)
    }

    static {
      defaultInstance = new TypeMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TypeMetadata)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TypeMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TypeMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/MetadataModel.proto\032 go" +
      "ogle/protobuf/descriptor.proto\"c\n\014TypeMe" +
      "tadata\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\0229\n\017type" +
      "_descriptor\030\003 \001(\0132 .google.protobuf.Desc" +
      "riptorProtoB\016\n\014com.cloudata"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TypeMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TypeMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TypeMetadata_descriptor,
              new java.lang.String[] { "Id", "Name", "TypeDescriptor", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
