// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/AuthModel.proto

package com.cloudata.auth;

public final class AuthModel {
  private AuthModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserCredentialDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string login = 1;
    /**
     * <code>optional string login = 1;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional string login = 1;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>optional string login = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    // optional .HashedPasswordData password_hashed = 2;
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    boolean hasPasswordHashed();
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    com.cloudata.auth.AuthModel.HashedPasswordData getPasswordHashed();
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder getPasswordHashedOrBuilder();

    // optional bytes user_id = 3;
    /**
     * <code>optional bytes user_id = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional bytes user_id = 3;</code>
     */
    com.google.protobuf.ByteString getUserId();
  }
  /**
   * Protobuf type {@code UserCredentialData}
   */
  public static final class UserCredentialData extends
      com.google.protobuf.GeneratedMessage
      implements UserCredentialDataOrBuilder {
    // Use UserCredentialData.newBuilder() to construct.
    private UserCredentialData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserCredentialData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserCredentialData defaultInstance;
    public static UserCredentialData getDefaultInstance() {
      return defaultInstance;
    }

    public UserCredentialData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserCredentialData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              login_ = input.readBytes();
              break;
            }
            case 18: {
              com.cloudata.auth.AuthModel.HashedPasswordData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = passwordHashed_.toBuilder();
              }
              passwordHashed_ = input.readMessage(com.cloudata.auth.AuthModel.HashedPasswordData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(passwordHashed_);
                passwordHashed_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.auth.AuthModel.internal_static_UserCredentialData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.auth.AuthModel.internal_static_UserCredentialData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.auth.AuthModel.UserCredentialData.class, com.cloudata.auth.AuthModel.UserCredentialData.Builder.class);
    }

    public static com.google.protobuf.Parser<UserCredentialData> PARSER =
        new com.google.protobuf.AbstractParser<UserCredentialData>() {
      public UserCredentialData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserCredentialData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserCredentialData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string login = 1;
    public static final int LOGIN_FIELD_NUMBER = 1;
    private java.lang.Object login_;
    /**
     * <code>optional string login = 1;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string login = 1;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          login_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .HashedPasswordData password_hashed = 2;
    public static final int PASSWORD_HASHED_FIELD_NUMBER = 2;
    private com.cloudata.auth.AuthModel.HashedPasswordData passwordHashed_;
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    public boolean hasPasswordHashed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    public com.cloudata.auth.AuthModel.HashedPasswordData getPasswordHashed() {
      return passwordHashed_;
    }
    /**
     * <code>optional .HashedPasswordData password_hashed = 2;</code>
     */
    public com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder getPasswordHashedOrBuilder() {
      return passwordHashed_;
    }

    // optional bytes user_id = 3;
    public static final int USER_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString userId_;
    /**
     * <code>optional bytes user_id = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes user_id = 3;</code>
     */
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }

    private void initFields() {
      login_ = "";
      passwordHashed_ = com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance();
      userId_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, passwordHashed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, passwordHashed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserCredentialData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.auth.AuthModel.UserCredentialData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserCredentialData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.auth.AuthModel.UserCredentialDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.auth.AuthModel.internal_static_UserCredentialData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.auth.AuthModel.internal_static_UserCredentialData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.auth.AuthModel.UserCredentialData.class, com.cloudata.auth.AuthModel.UserCredentialData.Builder.class);
      }

      // Construct using com.cloudata.auth.AuthModel.UserCredentialData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPasswordHashedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        login_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (passwordHashedBuilder_ == null) {
          passwordHashed_ = com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance();
        } else {
          passwordHashedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.auth.AuthModel.internal_static_UserCredentialData_descriptor;
      }

      public com.cloudata.auth.AuthModel.UserCredentialData getDefaultInstanceForType() {
        return com.cloudata.auth.AuthModel.UserCredentialData.getDefaultInstance();
      }

      public com.cloudata.auth.AuthModel.UserCredentialData build() {
        com.cloudata.auth.AuthModel.UserCredentialData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.auth.AuthModel.UserCredentialData buildPartial() {
        com.cloudata.auth.AuthModel.UserCredentialData result = new com.cloudata.auth.AuthModel.UserCredentialData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.login_ = login_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (passwordHashedBuilder_ == null) {
          result.passwordHashed_ = passwordHashed_;
        } else {
          result.passwordHashed_ = passwordHashedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.auth.AuthModel.UserCredentialData) {
          return mergeFrom((com.cloudata.auth.AuthModel.UserCredentialData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.auth.AuthModel.UserCredentialData other) {
        if (other == com.cloudata.auth.AuthModel.UserCredentialData.getDefaultInstance()) return this;
        if (other.hasLogin()) {
          bitField0_ |= 0x00000001;
          login_ = other.login_;
          onChanged();
        }
        if (other.hasPasswordHashed()) {
          mergePasswordHashed(other.getPasswordHashed());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.auth.AuthModel.UserCredentialData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.auth.AuthModel.UserCredentialData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string login = 1;
      private java.lang.Object login_ = "";
      /**
       * <code>optional string login = 1;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string login = 1;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login = 1;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 1;</code>
       */
      public Builder clearLogin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 1;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        login_ = value;
        onChanged();
        return this;
      }

      // optional .HashedPasswordData password_hashed = 2;
      private com.cloudata.auth.AuthModel.HashedPasswordData passwordHashed_ = com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudata.auth.AuthModel.HashedPasswordData, com.cloudata.auth.AuthModel.HashedPasswordData.Builder, com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder> passwordHashedBuilder_;
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public boolean hasPasswordHashed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public com.cloudata.auth.AuthModel.HashedPasswordData getPasswordHashed() {
        if (passwordHashedBuilder_ == null) {
          return passwordHashed_;
        } else {
          return passwordHashedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public Builder setPasswordHashed(com.cloudata.auth.AuthModel.HashedPasswordData value) {
        if (passwordHashedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          passwordHashed_ = value;
          onChanged();
        } else {
          passwordHashedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public Builder setPasswordHashed(
          com.cloudata.auth.AuthModel.HashedPasswordData.Builder builderForValue) {
        if (passwordHashedBuilder_ == null) {
          passwordHashed_ = builderForValue.build();
          onChanged();
        } else {
          passwordHashedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public Builder mergePasswordHashed(com.cloudata.auth.AuthModel.HashedPasswordData value) {
        if (passwordHashedBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              passwordHashed_ != com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance()) {
            passwordHashed_ =
              com.cloudata.auth.AuthModel.HashedPasswordData.newBuilder(passwordHashed_).mergeFrom(value).buildPartial();
          } else {
            passwordHashed_ = value;
          }
          onChanged();
        } else {
          passwordHashedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public Builder clearPasswordHashed() {
        if (passwordHashedBuilder_ == null) {
          passwordHashed_ = com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance();
          onChanged();
        } else {
          passwordHashedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public com.cloudata.auth.AuthModel.HashedPasswordData.Builder getPasswordHashedBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPasswordHashedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      public com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder getPasswordHashedOrBuilder() {
        if (passwordHashedBuilder_ != null) {
          return passwordHashedBuilder_.getMessageOrBuilder();
        } else {
          return passwordHashed_;
        }
      }
      /**
       * <code>optional .HashedPasswordData password_hashed = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudata.auth.AuthModel.HashedPasswordData, com.cloudata.auth.AuthModel.HashedPasswordData.Builder, com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder> 
          getPasswordHashedFieldBuilder() {
        if (passwordHashedBuilder_ == null) {
          passwordHashedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cloudata.auth.AuthModel.HashedPasswordData, com.cloudata.auth.AuthModel.HashedPasswordData.Builder, com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder>(
                  passwordHashed_,
                  getParentForChildren(),
                  isClean());
          passwordHashed_ = null;
        }
        return passwordHashedBuilder_;
      }

      // optional bytes user_id = 3;
      private com.google.protobuf.ByteString userId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_id = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes user_id = 3;</code>
       */
      public com.google.protobuf.ByteString getUserId() {
        return userId_;
      }
      /**
       * <code>optional bytes user_id = 3;</code>
       */
      public Builder setUserId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_id = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserCredentialData)
    }

    static {
      defaultInstance = new UserCredentialData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UserCredentialData)
  }

  public interface UserDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes id = 1;
    /**
     * <code>optional bytes id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code UserData}
   */
  public static final class UserData extends
      com.google.protobuf.GeneratedMessage
      implements UserDataOrBuilder {
    // Use UserData.newBuilder() to construct.
    private UserData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserData defaultInstance;
    public static UserData getDefaultInstance() {
      return defaultInstance;
    }

    public UserData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.auth.AuthModel.internal_static_UserData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.auth.AuthModel.internal_static_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.auth.AuthModel.UserData.class, com.cloudata.auth.AuthModel.UserData.Builder.class);
    }

    public static com.google.protobuf.Parser<UserData> PARSER =
        new com.google.protobuf.AbstractParser<UserData>() {
      public UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.auth.AuthModel.UserData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.auth.AuthModel.UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.auth.AuthModel.internal_static_UserData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.auth.AuthModel.internal_static_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.auth.AuthModel.UserData.class, com.cloudata.auth.AuthModel.UserData.Builder.class);
      }

      // Construct using com.cloudata.auth.AuthModel.UserData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.auth.AuthModel.internal_static_UserData_descriptor;
      }

      public com.cloudata.auth.AuthModel.UserData getDefaultInstanceForType() {
        return com.cloudata.auth.AuthModel.UserData.getDefaultInstance();
      }

      public com.cloudata.auth.AuthModel.UserData build() {
        com.cloudata.auth.AuthModel.UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.auth.AuthModel.UserData buildPartial() {
        com.cloudata.auth.AuthModel.UserData result = new com.cloudata.auth.AuthModel.UserData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.auth.AuthModel.UserData) {
          return mergeFrom((com.cloudata.auth.AuthModel.UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.auth.AuthModel.UserData other) {
        if (other == com.cloudata.auth.AuthModel.UserData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.auth.AuthModel.UserData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.auth.AuthModel.UserData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes id = 1;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserData)
    }

    static {
      defaultInstance = new UserData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UserData)
  }

  public interface HashedPasswordDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes salt = 2;
    /**
     * <code>optional bytes salt = 2;</code>
     *
     * <pre>
     *optional algorithm  = 1;
     * </pre>
     */
    boolean hasSalt();
    /**
     * <code>optional bytes salt = 2;</code>
     *
     * <pre>
     *optional algorithm  = 1;
     * </pre>
     */
    com.google.protobuf.ByteString getSalt();

    // optional int32 iterations = 3;
    /**
     * <code>optional int32 iterations = 3;</code>
     */
    boolean hasIterations();
    /**
     * <code>optional int32 iterations = 3;</code>
     */
    int getIterations();

    // optional bytes hashed = 4;
    /**
     * <code>optional bytes hashed = 4;</code>
     */
    boolean hasHashed();
    /**
     * <code>optional bytes hashed = 4;</code>
     */
    com.google.protobuf.ByteString getHashed();
  }
  /**
   * Protobuf type {@code HashedPasswordData}
   */
  public static final class HashedPasswordData extends
      com.google.protobuf.GeneratedMessage
      implements HashedPasswordDataOrBuilder {
    // Use HashedPasswordData.newBuilder() to construct.
    private HashedPasswordData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HashedPasswordData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HashedPasswordData defaultInstance;
    public static HashedPasswordData getDefaultInstance() {
      return defaultInstance;
    }

    public HashedPasswordData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HashedPasswordData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              salt_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              iterations_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              hashed_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.auth.AuthModel.internal_static_HashedPasswordData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.auth.AuthModel.internal_static_HashedPasswordData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.auth.AuthModel.HashedPasswordData.class, com.cloudata.auth.AuthModel.HashedPasswordData.Builder.class);
    }

    public static com.google.protobuf.Parser<HashedPasswordData> PARSER =
        new com.google.protobuf.AbstractParser<HashedPasswordData>() {
      public HashedPasswordData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HashedPasswordData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HashedPasswordData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes salt = 2;
    public static final int SALT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString salt_;
    /**
     * <code>optional bytes salt = 2;</code>
     *
     * <pre>
     *optional algorithm  = 1;
     * </pre>
     */
    public boolean hasSalt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes salt = 2;</code>
     *
     * <pre>
     *optional algorithm  = 1;
     * </pre>
     */
    public com.google.protobuf.ByteString getSalt() {
      return salt_;
    }

    // optional int32 iterations = 3;
    public static final int ITERATIONS_FIELD_NUMBER = 3;
    private int iterations_;
    /**
     * <code>optional int32 iterations = 3;</code>
     */
    public boolean hasIterations() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 iterations = 3;</code>
     */
    public int getIterations() {
      return iterations_;
    }

    // optional bytes hashed = 4;
    public static final int HASHED_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString hashed_;
    /**
     * <code>optional bytes hashed = 4;</code>
     */
    public boolean hasHashed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes hashed = 4;</code>
     */
    public com.google.protobuf.ByteString getHashed() {
      return hashed_;
    }

    private void initFields() {
      salt_ = com.google.protobuf.ByteString.EMPTY;
      iterations_ = 0;
      hashed_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, salt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, iterations_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, hashed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, salt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, iterations_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, hashed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.auth.AuthModel.HashedPasswordData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.auth.AuthModel.HashedPasswordData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HashedPasswordData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.auth.AuthModel.HashedPasswordDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.auth.AuthModel.internal_static_HashedPasswordData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.auth.AuthModel.internal_static_HashedPasswordData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.auth.AuthModel.HashedPasswordData.class, com.cloudata.auth.AuthModel.HashedPasswordData.Builder.class);
      }

      // Construct using com.cloudata.auth.AuthModel.HashedPasswordData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        salt_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        iterations_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hashed_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.auth.AuthModel.internal_static_HashedPasswordData_descriptor;
      }

      public com.cloudata.auth.AuthModel.HashedPasswordData getDefaultInstanceForType() {
        return com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance();
      }

      public com.cloudata.auth.AuthModel.HashedPasswordData build() {
        com.cloudata.auth.AuthModel.HashedPasswordData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.auth.AuthModel.HashedPasswordData buildPartial() {
        com.cloudata.auth.AuthModel.HashedPasswordData result = new com.cloudata.auth.AuthModel.HashedPasswordData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.salt_ = salt_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iterations_ = iterations_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hashed_ = hashed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.auth.AuthModel.HashedPasswordData) {
          return mergeFrom((com.cloudata.auth.AuthModel.HashedPasswordData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.auth.AuthModel.HashedPasswordData other) {
        if (other == com.cloudata.auth.AuthModel.HashedPasswordData.getDefaultInstance()) return this;
        if (other.hasSalt()) {
          setSalt(other.getSalt());
        }
        if (other.hasIterations()) {
          setIterations(other.getIterations());
        }
        if (other.hasHashed()) {
          setHashed(other.getHashed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.auth.AuthModel.HashedPasswordData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.auth.AuthModel.HashedPasswordData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes salt = 2;
      private com.google.protobuf.ByteString salt_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes salt = 2;</code>
       *
       * <pre>
       *optional algorithm  = 1;
       * </pre>
       */
      public boolean hasSalt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes salt = 2;</code>
       *
       * <pre>
       *optional algorithm  = 1;
       * </pre>
       */
      public com.google.protobuf.ByteString getSalt() {
        return salt_;
      }
      /**
       * <code>optional bytes salt = 2;</code>
       *
       * <pre>
       *optional algorithm  = 1;
       * </pre>
       */
      public Builder setSalt(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        salt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes salt = 2;</code>
       *
       * <pre>
       *optional algorithm  = 1;
       * </pre>
       */
      public Builder clearSalt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        salt_ = getDefaultInstance().getSalt();
        onChanged();
        return this;
      }

      // optional int32 iterations = 3;
      private int iterations_ ;
      /**
       * <code>optional int32 iterations = 3;</code>
       */
      public boolean hasIterations() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 iterations = 3;</code>
       */
      public int getIterations() {
        return iterations_;
      }
      /**
       * <code>optional int32 iterations = 3;</code>
       */
      public Builder setIterations(int value) {
        bitField0_ |= 0x00000002;
        iterations_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iterations = 3;</code>
       */
      public Builder clearIterations() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iterations_ = 0;
        onChanged();
        return this;
      }

      // optional bytes hashed = 4;
      private com.google.protobuf.ByteString hashed_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hashed = 4;</code>
       */
      public boolean hasHashed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes hashed = 4;</code>
       */
      public com.google.protobuf.ByteString getHashed() {
        return hashed_;
      }
      /**
       * <code>optional bytes hashed = 4;</code>
       */
      public Builder setHashed(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hashed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hashed = 4;</code>
       */
      public Builder clearHashed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hashed_ = getDefaultInstance().getHashed();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HashedPasswordData)
    }

    static {
      defaultInstance = new HashedPasswordData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HashedPasswordData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserCredentialData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserCredentialData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HashedPasswordData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HashedPasswordData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/AuthModel.proto\"b\n\022User" +
      "CredentialData\022\r\n\005login\030\001 \001(\t\022,\n\017passwor" +
      "d_hashed\030\002 \001(\0132\023.HashedPasswordData\022\017\n\007u" +
      "ser_id\030\003 \001(\014\"$\n\010UserData\022\n\n\002id\030\001 \001(\014\022\014\n\004" +
      "name\030\002 \001(\t\"F\n\022HashedPasswordData\022\014\n\004salt" +
      "\030\002 \001(\014\022\022\n\niterations\030\003 \001(\005\022\016\n\006hashed\030\004 \001" +
      "(\014B\023\n\021com.cloudata.auth"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_UserCredentialData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_UserCredentialData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserCredentialData_descriptor,
              new java.lang.String[] { "Login", "PasswordHashed", "UserId", });
          internal_static_UserData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_UserData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserData_descriptor,
              new java.lang.String[] { "Id", "Name", });
          internal_static_HashedPasswordData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HashedPasswordData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HashedPasswordData_descriptor,
              new java.lang.String[] { "Salt", "Iterations", "Hashed", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
