// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GitModel.proto

package com.cloudata.git;

public final class GitModel {
  private GitModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code TargetType}
   */
  public enum TargetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TARGET_TYPE_REPO_NAME = 1;</code>
     */
    TARGET_TYPE_REPO_NAME(0, 1),
    ;

    /**
     * <code>TARGET_TYPE_REPO_NAME = 1;</code>
     */
    public static final int TARGET_TYPE_REPO_NAME_VALUE = 1;


    public final int getNumber() { return value; }

    public static TargetType valueOf(int value) {
      switch (value) {
        case 1: return TARGET_TYPE_REPO_NAME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TargetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TargetType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TargetType>() {
            public TargetType findValueByNumber(int number) {
              return TargetType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cloudata.git.GitModel.getDescriptor().getEnumTypes().get(0);
    }

    private static final TargetType[] VALUES = values();

    public static TargetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TargetType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TargetType)
  }

  public interface RefDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes repository_id = 1;
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    boolean hasRepositoryId();
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    com.google.protobuf.ByteString getRepositoryId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string target_name = 3;
    /**
     * <code>optional string target_name = 3;</code>
     */
    boolean hasTargetName();
    /**
     * <code>optional string target_name = 3;</code>
     */
    java.lang.String getTargetName();
    /**
     * <code>optional string target_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getTargetNameBytes();

    // optional bytes object_id = 4;
    /**
     * <code>optional bytes object_id = 4;</code>
     */
    boolean hasObjectId();
    /**
     * <code>optional bytes object_id = 4;</code>
     */
    com.google.protobuf.ByteString getObjectId();
  }
  /**
   * Protobuf type {@code RefData}
   */
  public static final class RefData extends
      com.google.protobuf.GeneratedMessage
      implements RefDataOrBuilder {
    // Use RefData.newBuilder() to construct.
    private RefData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RefData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RefData defaultInstance;
    public static RefData getDefaultInstance() {
      return defaultInstance;
    }

    public RefData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RefData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              repositoryId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              targetName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              objectId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.git.GitModel.internal_static_RefData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.git.GitModel.internal_static_RefData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.git.GitModel.RefData.class, com.cloudata.git.GitModel.RefData.Builder.class);
    }

    public static com.google.protobuf.Parser<RefData> PARSER =
        new com.google.protobuf.AbstractParser<RefData>() {
      public RefData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RefData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RefData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes repository_id = 1;
    public static final int REPOSITORY_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString repositoryId_;
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    public boolean hasRepositoryId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    public com.google.protobuf.ByteString getRepositoryId() {
      return repositoryId_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string target_name = 3;
    public static final int TARGET_NAME_FIELD_NUMBER = 3;
    private java.lang.Object targetName_;
    /**
     * <code>optional string target_name = 3;</code>
     */
    public boolean hasTargetName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string target_name = 3;</code>
     */
    public java.lang.String getTargetName() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetNameBytes() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes object_id = 4;
    public static final int OBJECT_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString objectId_;
    /**
     * <code>optional bytes object_id = 4;</code>
     */
    public boolean hasObjectId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes object_id = 4;</code>
     */
    public com.google.protobuf.ByteString getObjectId() {
      return objectId_;
    }

    private void initFields() {
      repositoryId_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      targetName_ = "";
      objectId_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, repositoryId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, objectId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, repositoryId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, objectId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.git.GitModel.RefData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RefData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.git.GitModel.RefData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.RefData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.git.GitModel.RefData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RefData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.git.GitModel.RefDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.git.GitModel.internal_static_RefData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.git.GitModel.internal_static_RefData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.git.GitModel.RefData.class, com.cloudata.git.GitModel.RefData.Builder.class);
      }

      // Construct using com.cloudata.git.GitModel.RefData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        repositoryId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        targetName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        objectId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.git.GitModel.internal_static_RefData_descriptor;
      }

      public com.cloudata.git.GitModel.RefData getDefaultInstanceForType() {
        return com.cloudata.git.GitModel.RefData.getDefaultInstance();
      }

      public com.cloudata.git.GitModel.RefData build() {
        com.cloudata.git.GitModel.RefData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.git.GitModel.RefData buildPartial() {
        com.cloudata.git.GitModel.RefData result = new com.cloudata.git.GitModel.RefData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.repositoryId_ = repositoryId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetName_ = targetName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.objectId_ = objectId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.git.GitModel.RefData) {
          return mergeFrom((com.cloudata.git.GitModel.RefData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.git.GitModel.RefData other) {
        if (other == com.cloudata.git.GitModel.RefData.getDefaultInstance()) return this;
        if (other.hasRepositoryId()) {
          setRepositoryId(other.getRepositoryId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTargetName()) {
          bitField0_ |= 0x00000004;
          targetName_ = other.targetName_;
          onChanged();
        }
        if (other.hasObjectId()) {
          setObjectId(other.getObjectId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.git.GitModel.RefData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.git.GitModel.RefData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes repository_id = 1;
      private com.google.protobuf.ByteString repositoryId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public boolean hasRepositoryId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public com.google.protobuf.ByteString getRepositoryId() {
        return repositoryId_;
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public Builder setRepositoryId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        repositoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public Builder clearRepositoryId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        repositoryId_ = getDefaultInstance().getRepositoryId();
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string target_name = 3;
      private java.lang.Object targetName_ = "";
      /**
       * <code>optional string target_name = 3;</code>
       */
      public boolean hasTargetName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string target_name = 3;</code>
       */
      public java.lang.String getTargetName() {
        java.lang.Object ref = targetName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTargetNameBytes() {
        java.lang.Object ref = targetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target_name = 3;</code>
       */
      public Builder setTargetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_name = 3;</code>
       */
      public Builder clearTargetName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetName_ = getDefaultInstance().getTargetName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_name = 3;</code>
       */
      public Builder setTargetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetName_ = value;
        onChanged();
        return this;
      }

      // optional bytes object_id = 4;
      private com.google.protobuf.ByteString objectId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes object_id = 4;</code>
       */
      public boolean hasObjectId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes object_id = 4;</code>
       */
      public com.google.protobuf.ByteString getObjectId() {
        return objectId_;
      }
      /**
       * <code>optional bytes object_id = 4;</code>
       */
      public Builder setObjectId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes object_id = 4;</code>
       */
      public Builder clearObjectId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RefData)
    }

    static {
      defaultInstance = new RefData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RefData)
  }

  public interface RepositoryDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 3;
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes repository_id = 1;
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    boolean hasRepositoryId();
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    com.google.protobuf.ByteString getRepositoryId();

    // optional bytes owner_id = 2;
    /**
     * <code>optional bytes owner_id = 2;</code>
     */
    boolean hasOwnerId();
    /**
     * <code>optional bytes owner_id = 2;</code>
     */
    com.google.protobuf.ByteString getOwnerId();
  }
  /**
   * Protobuf type {@code RepositoryData}
   */
  public static final class RepositoryData extends
      com.google.protobuf.GeneratedMessage
      implements RepositoryDataOrBuilder {
    // Use RepositoryData.newBuilder() to construct.
    private RepositoryData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RepositoryData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RepositoryData defaultInstance;
    public static RepositoryData getDefaultInstance() {
      return defaultInstance;
    }

    public RepositoryData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RepositoryData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000002;
              repositoryId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000004;
              ownerId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.git.GitModel.internal_static_RepositoryData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.git.GitModel.internal_static_RepositoryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.git.GitModel.RepositoryData.class, com.cloudata.git.GitModel.RepositoryData.Builder.class);
    }

    public static com.google.protobuf.Parser<RepositoryData> PARSER =
        new com.google.protobuf.AbstractParser<RepositoryData>() {
      public RepositoryData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RepositoryData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RepositoryData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * pk
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes repository_id = 1;
    public static final int REPOSITORY_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString repositoryId_;
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    public boolean hasRepositoryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes repository_id = 1;</code>
     */
    public com.google.protobuf.ByteString getRepositoryId() {
      return repositoryId_;
    }

    // optional bytes owner_id = 2;
    public static final int OWNER_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString ownerId_;
    /**
     * <code>optional bytes owner_id = 2;</code>
     */
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes owner_id = 2;</code>
     */
    public com.google.protobuf.ByteString getOwnerId() {
      return ownerId_;
    }

    private void initFields() {
      name_ = "";
      repositoryId_ = com.google.protobuf.ByteString.EMPTY;
      ownerId_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(1, repositoryId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(2, ownerId_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(3, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, repositoryId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, ownerId_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.RepositoryData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.git.GitModel.RepositoryData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RepositoryData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.git.GitModel.RepositoryDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.git.GitModel.internal_static_RepositoryData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.git.GitModel.internal_static_RepositoryData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.git.GitModel.RepositoryData.class, com.cloudata.git.GitModel.RepositoryData.Builder.class);
      }

      // Construct using com.cloudata.git.GitModel.RepositoryData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        repositoryId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.git.GitModel.internal_static_RepositoryData_descriptor;
      }

      public com.cloudata.git.GitModel.RepositoryData getDefaultInstanceForType() {
        return com.cloudata.git.GitModel.RepositoryData.getDefaultInstance();
      }

      public com.cloudata.git.GitModel.RepositoryData build() {
        com.cloudata.git.GitModel.RepositoryData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.git.GitModel.RepositoryData buildPartial() {
        com.cloudata.git.GitModel.RepositoryData result = new com.cloudata.git.GitModel.RepositoryData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.repositoryId_ = repositoryId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ownerId_ = ownerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.git.GitModel.RepositoryData) {
          return mergeFrom((com.cloudata.git.GitModel.RepositoryData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.git.GitModel.RepositoryData other) {
        if (other == com.cloudata.git.GitModel.RepositoryData.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRepositoryId()) {
          setRepositoryId(other.getRepositoryId());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.git.GitModel.RepositoryData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.git.GitModel.RepositoryData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * pk
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes repository_id = 1;
      private com.google.protobuf.ByteString repositoryId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public boolean hasRepositoryId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public com.google.protobuf.ByteString getRepositoryId() {
        return repositoryId_;
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public Builder setRepositoryId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        repositoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes repository_id = 1;</code>
       */
      public Builder clearRepositoryId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        repositoryId_ = getDefaultInstance().getRepositoryId();
        onChanged();
        return this;
      }

      // optional bytes owner_id = 2;
      private com.google.protobuf.ByteString ownerId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes owner_id = 2;</code>
       */
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes owner_id = 2;</code>
       */
      public com.google.protobuf.ByteString getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>optional bytes owner_id = 2;</code>
       */
      public Builder setOwnerId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes owner_id = 2;</code>
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = getDefaultInstance().getOwnerId();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RepositoryData)
    }

    static {
      defaultInstance = new RepositoryData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RepositoryData)
  }

  public interface UserAclOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes user_id = 1;
    /**
     * <code>optional bytes user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional bytes user_id = 1;</code>
     */
    com.google.protobuf.ByteString getUserId();

    // optional .TargetType target_type = 2;
    /**
     * <code>optional .TargetType target_type = 2;</code>
     */
    boolean hasTargetType();
    /**
     * <code>optional .TargetType target_type = 2;</code>
     */
    com.cloudata.git.GitModel.TargetType getTargetType();

    // optional bytes target_id = 3;
    /**
     * <code>optional bytes target_id = 3;</code>
     */
    boolean hasTargetId();
    /**
     * <code>optional bytes target_id = 3;</code>
     */
    com.google.protobuf.ByteString getTargetId();

    // optional bool owner = 4;
    /**
     * <code>optional bool owner = 4;</code>
     */
    boolean hasOwner();
    /**
     * <code>optional bool owner = 4;</code>
     */
    boolean getOwner();
  }
  /**
   * Protobuf type {@code UserAcl}
   */
  public static final class UserAcl extends
      com.google.protobuf.GeneratedMessage
      implements UserAclOrBuilder {
    // Use UserAcl.newBuilder() to construct.
    private UserAcl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserAcl(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserAcl defaultInstance;
    public static UserAcl getDefaultInstance() {
      return defaultInstance;
    }

    public UserAcl getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserAcl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.cloudata.git.GitModel.TargetType value = com.cloudata.git.GitModel.TargetType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                targetType_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              targetId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              owner_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.git.GitModel.internal_static_UserAcl_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.git.GitModel.internal_static_UserAcl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.git.GitModel.UserAcl.class, com.cloudata.git.GitModel.UserAcl.Builder.class);
    }

    public static com.google.protobuf.Parser<UserAcl> PARSER =
        new com.google.protobuf.AbstractParser<UserAcl>() {
      public UserAcl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserAcl(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserAcl> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString userId_;
    /**
     * <code>optional bytes user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes user_id = 1;</code>
     */
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }

    // optional .TargetType target_type = 2;
    public static final int TARGET_TYPE_FIELD_NUMBER = 2;
    private com.cloudata.git.GitModel.TargetType targetType_;
    /**
     * <code>optional .TargetType target_type = 2;</code>
     */
    public boolean hasTargetType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .TargetType target_type = 2;</code>
     */
    public com.cloudata.git.GitModel.TargetType getTargetType() {
      return targetType_;
    }

    // optional bytes target_id = 3;
    public static final int TARGET_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString targetId_;
    /**
     * <code>optional bytes target_id = 3;</code>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes target_id = 3;</code>
     */
    public com.google.protobuf.ByteString getTargetId() {
      return targetId_;
    }

    // optional bool owner = 4;
    public static final int OWNER_FIELD_NUMBER = 4;
    private boolean owner_;
    /**
     * <code>optional bool owner = 4;</code>
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool owner = 4;</code>
     */
    public boolean getOwner() {
      return owner_;
    }

    private void initFields() {
      userId_ = com.google.protobuf.ByteString.EMPTY;
      targetType_ = com.cloudata.git.GitModel.TargetType.TARGET_TYPE_REPO_NAME;
      targetId_ = com.google.protobuf.ByteString.EMPTY;
      owner_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, targetType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, targetId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, owner_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, targetType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, targetId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, owner_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.UserAcl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.git.GitModel.UserAcl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.git.GitModel.UserAcl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.git.GitModel.UserAcl prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserAcl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudata.git.GitModel.UserAclOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.git.GitModel.internal_static_UserAcl_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.git.GitModel.internal_static_UserAcl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.git.GitModel.UserAcl.class, com.cloudata.git.GitModel.UserAcl.Builder.class);
      }

      // Construct using com.cloudata.git.GitModel.UserAcl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        targetType_ = com.cloudata.git.GitModel.TargetType.TARGET_TYPE_REPO_NAME;
        bitField0_ = (bitField0_ & ~0x00000002);
        targetId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        owner_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.git.GitModel.internal_static_UserAcl_descriptor;
      }

      public com.cloudata.git.GitModel.UserAcl getDefaultInstanceForType() {
        return com.cloudata.git.GitModel.UserAcl.getDefaultInstance();
      }

      public com.cloudata.git.GitModel.UserAcl build() {
        com.cloudata.git.GitModel.UserAcl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.git.GitModel.UserAcl buildPartial() {
        com.cloudata.git.GitModel.UserAcl result = new com.cloudata.git.GitModel.UserAcl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetType_ = targetType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetId_ = targetId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.owner_ = owner_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.git.GitModel.UserAcl) {
          return mergeFrom((com.cloudata.git.GitModel.UserAcl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.git.GitModel.UserAcl other) {
        if (other == com.cloudata.git.GitModel.UserAcl.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasTargetType()) {
          setTargetType(other.getTargetType());
        }
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        if (other.hasOwner()) {
          setOwner(other.getOwner());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.git.GitModel.UserAcl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.git.GitModel.UserAcl) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes user_id = 1;
      private com.google.protobuf.ByteString userId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes user_id = 1;</code>
       */
      public com.google.protobuf.ByteString getUserId() {
        return userId_;
      }
      /**
       * <code>optional bytes user_id = 1;</code>
       */
      public Builder setUserId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }

      // optional .TargetType target_type = 2;
      private com.cloudata.git.GitModel.TargetType targetType_ = com.cloudata.git.GitModel.TargetType.TARGET_TYPE_REPO_NAME;
      /**
       * <code>optional .TargetType target_type = 2;</code>
       */
      public boolean hasTargetType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .TargetType target_type = 2;</code>
       */
      public com.cloudata.git.GitModel.TargetType getTargetType() {
        return targetType_;
      }
      /**
       * <code>optional .TargetType target_type = 2;</code>
       */
      public Builder setTargetType(com.cloudata.git.GitModel.TargetType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        targetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .TargetType target_type = 2;</code>
       */
      public Builder clearTargetType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetType_ = com.cloudata.git.GitModel.TargetType.TARGET_TYPE_REPO_NAME;
        onChanged();
        return this;
      }

      // optional bytes target_id = 3;
      private com.google.protobuf.ByteString targetId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes target_id = 3;</code>
       */
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes target_id = 3;</code>
       */
      public com.google.protobuf.ByteString getTargetId() {
        return targetId_;
      }
      /**
       * <code>optional bytes target_id = 3;</code>
       */
      public Builder setTargetId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes target_id = 3;</code>
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetId_ = getDefaultInstance().getTargetId();
        onChanged();
        return this;
      }

      // optional bool owner = 4;
      private boolean owner_ ;
      /**
       * <code>optional bool owner = 4;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool owner = 4;</code>
       */
      public boolean getOwner() {
        return owner_;
      }
      /**
       * <code>optional bool owner = 4;</code>
       */
      public Builder setOwner(boolean value) {
        bitField0_ |= 0x00000008;
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool owner = 4;</code>
       */
      public Builder clearOwner() {
        bitField0_ = (bitField0_ & ~0x00000008);
        owner_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserAcl)
    }

    static {
      defaultInstance = new UserAcl(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UserAcl)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RefData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RefData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RepositoryData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RepositoryData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserAcl_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserAcl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/GitModel.proto\"V\n\007RefDa" +
      "ta\022\025\n\rrepository_id\030\001 \001(\014\022\014\n\004name\030\002 \001(\t\022" +
      "\023\n\013target_name\030\003 \001(\t\022\021\n\tobject_id\030\004 \001(\014\"" +
      "G\n\016RepositoryData\022\014\n\004name\030\003 \001(\t\022\025\n\rrepos" +
      "itory_id\030\001 \001(\014\022\020\n\010owner_id\030\002 \001(\014\"^\n\007User" +
      "Acl\022\017\n\007user_id\030\001 \001(\014\022 \n\013target_type\030\002 \001(" +
      "\0162\013.TargetType\022\021\n\ttarget_id\030\003 \001(\014\022\r\n\005own" +
      "er\030\004 \001(\010*\'\n\nTargetType\022\031\n\025TARGET_TYPE_RE" +
      "PO_NAME\020\001B\022\n\020com.cloudata.git"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RefData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RefData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RefData_descriptor,
              new java.lang.String[] { "RepositoryId", "Name", "TargetName", "ObjectId", });
          internal_static_RepositoryData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RepositoryData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RepositoryData_descriptor,
              new java.lang.String[] { "Name", "RepositoryId", "OwnerId", });
          internal_static_UserAcl_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_UserAcl_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserAcl_descriptor,
              new java.lang.String[] { "UserId", "TargetType", "TargetId", "Owner", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
