// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/VolumeProto.proto

package com.cloudata.blockstore;

public final class VolumeProto {
  private VolumeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VolumeDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VolumeData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 segment_count = 2;</code>
     */
    boolean hasSegmentCount();
    /**
     * <code>optional uint32 segment_count = 2;</code>
     */
    int getSegmentCount();

    /**
     * <code>optional uint32 segment_size = 3;</code>
     */
    boolean hasSegmentSize();
    /**
     * <code>optional uint32 segment_size = 3;</code>
     */
    int getSegmentSize();

    /**
     * <code>optional bytes segment_store_id = 4;</code>
     */
    boolean hasSegmentStoreId();
    /**
     * <code>optional bytes segment_store_id = 4;</code>
     */
    com.google.protobuf.ByteString getSegmentStoreId();

    /**
     * <code>optional bytes blob_store_id = 5;</code>
     */
    boolean hasBlobStoreId();
    /**
     * <code>optional bytes blob_store_id = 5;</code>
     */
    com.google.protobuf.ByteString getBlobStoreId();
  }
  /**
   * Protobuf type {@code VolumeData}
   */
  public static final class VolumeData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VolumeData)
      VolumeDataOrBuilder {
    // Use VolumeData.newBuilder() to construct.
    private VolumeData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VolumeData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VolumeData defaultInstance;
    public static VolumeData getDefaultInstance() {
      return defaultInstance;
    }

    public VolumeData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VolumeData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              segmentCount_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              segmentSize_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              segmentStoreId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              blobStoreId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.blockstore.VolumeProto.internal_static_VolumeData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.blockstore.VolumeProto.internal_static_VolumeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.blockstore.VolumeProto.VolumeData.class, com.cloudata.blockstore.VolumeProto.VolumeData.Builder.class);
    }

    public static com.google.protobuf.Parser<VolumeData> PARSER =
        new com.google.protobuf.AbstractParser<VolumeData>() {
      public VolumeData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VolumeData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VolumeData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEGMENT_COUNT_FIELD_NUMBER = 2;
    private int segmentCount_;
    /**
     * <code>optional uint32 segment_count = 2;</code>
     */
    public boolean hasSegmentCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 segment_count = 2;</code>
     */
    public int getSegmentCount() {
      return segmentCount_;
    }

    public static final int SEGMENT_SIZE_FIELD_NUMBER = 3;
    private int segmentSize_;
    /**
     * <code>optional uint32 segment_size = 3;</code>
     */
    public boolean hasSegmentSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 segment_size = 3;</code>
     */
    public int getSegmentSize() {
      return segmentSize_;
    }

    public static final int SEGMENT_STORE_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString segmentStoreId_;
    /**
     * <code>optional bytes segment_store_id = 4;</code>
     */
    public boolean hasSegmentStoreId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes segment_store_id = 4;</code>
     */
    public com.google.protobuf.ByteString getSegmentStoreId() {
      return segmentStoreId_;
    }

    public static final int BLOB_STORE_ID_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString blobStoreId_;
    /**
     * <code>optional bytes blob_store_id = 5;</code>
     */
    public boolean hasBlobStoreId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes blob_store_id = 5;</code>
     */
    public com.google.protobuf.ByteString getBlobStoreId() {
      return blobStoreId_;
    }

    private void initFields() {
      segmentCount_ = 0;
      segmentSize_ = 0;
      segmentStoreId_ = com.google.protobuf.ByteString.EMPTY;
      blobStoreId_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(2, segmentCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(3, segmentSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, segmentStoreId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, blobStoreId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, segmentCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, segmentSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, segmentStoreId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, blobStoreId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.VolumeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.blockstore.VolumeProto.VolumeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VolumeData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VolumeData)
        com.cloudata.blockstore.VolumeProto.VolumeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.blockstore.VolumeProto.internal_static_VolumeData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.blockstore.VolumeProto.internal_static_VolumeData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.blockstore.VolumeProto.VolumeData.class, com.cloudata.blockstore.VolumeProto.VolumeData.Builder.class);
      }

      // Construct using com.cloudata.blockstore.VolumeProto.VolumeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        segmentCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        segmentSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        segmentStoreId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        blobStoreId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.blockstore.VolumeProto.internal_static_VolumeData_descriptor;
      }

      public com.cloudata.blockstore.VolumeProto.VolumeData getDefaultInstanceForType() {
        return com.cloudata.blockstore.VolumeProto.VolumeData.getDefaultInstance();
      }

      public com.cloudata.blockstore.VolumeProto.VolumeData build() {
        com.cloudata.blockstore.VolumeProto.VolumeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.blockstore.VolumeProto.VolumeData buildPartial() {
        com.cloudata.blockstore.VolumeProto.VolumeData result = new com.cloudata.blockstore.VolumeProto.VolumeData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.segmentCount_ = segmentCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.segmentSize_ = segmentSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.segmentStoreId_ = segmentStoreId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blobStoreId_ = blobStoreId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.blockstore.VolumeProto.VolumeData) {
          return mergeFrom((com.cloudata.blockstore.VolumeProto.VolumeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.blockstore.VolumeProto.VolumeData other) {
        if (other == com.cloudata.blockstore.VolumeProto.VolumeData.getDefaultInstance()) return this;
        if (other.hasSegmentCount()) {
          setSegmentCount(other.getSegmentCount());
        }
        if (other.hasSegmentSize()) {
          setSegmentSize(other.getSegmentSize());
        }
        if (other.hasSegmentStoreId()) {
          setSegmentStoreId(other.getSegmentStoreId());
        }
        if (other.hasBlobStoreId()) {
          setBlobStoreId(other.getBlobStoreId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.blockstore.VolumeProto.VolumeData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.blockstore.VolumeProto.VolumeData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int segmentCount_ ;
      /**
       * <code>optional uint32 segment_count = 2;</code>
       */
      public boolean hasSegmentCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 segment_count = 2;</code>
       */
      public int getSegmentCount() {
        return segmentCount_;
      }
      /**
       * <code>optional uint32 segment_count = 2;</code>
       */
      public Builder setSegmentCount(int value) {
        bitField0_ |= 0x00000001;
        segmentCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 segment_count = 2;</code>
       */
      public Builder clearSegmentCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        segmentCount_ = 0;
        onChanged();
        return this;
      }

      private int segmentSize_ ;
      /**
       * <code>optional uint32 segment_size = 3;</code>
       */
      public boolean hasSegmentSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 segment_size = 3;</code>
       */
      public int getSegmentSize() {
        return segmentSize_;
      }
      /**
       * <code>optional uint32 segment_size = 3;</code>
       */
      public Builder setSegmentSize(int value) {
        bitField0_ |= 0x00000002;
        segmentSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 segment_size = 3;</code>
       */
      public Builder clearSegmentSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        segmentSize_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString segmentStoreId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes segment_store_id = 4;</code>
       */
      public boolean hasSegmentStoreId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes segment_store_id = 4;</code>
       */
      public com.google.protobuf.ByteString getSegmentStoreId() {
        return segmentStoreId_;
      }
      /**
       * <code>optional bytes segment_store_id = 4;</code>
       */
      public Builder setSegmentStoreId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        segmentStoreId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes segment_store_id = 4;</code>
       */
      public Builder clearSegmentStoreId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        segmentStoreId_ = getDefaultInstance().getSegmentStoreId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString blobStoreId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes blob_store_id = 5;</code>
       */
      public boolean hasBlobStoreId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes blob_store_id = 5;</code>
       */
      public com.google.protobuf.ByteString getBlobStoreId() {
        return blobStoreId_;
      }
      /**
       * <code>optional bytes blob_store_id = 5;</code>
       */
      public Builder setBlobStoreId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        blobStoreId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes blob_store_id = 5;</code>
       */
      public Builder clearBlobStoreId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blobStoreId_ = getDefaultInstance().getBlobStoreId();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VolumeData)
    }

    static {
      defaultInstance = new VolumeData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VolumeData)
  }

  public interface SegmentDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SegmentData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 offset = 1;</code>
     */
    boolean hasOffset();
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    long getOffset();

    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData> 
        getChunkList();
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    com.cloudata.blockstore.VolumeProto.ChunkData getChunk(int index);
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    int getChunkCount();
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    java.util.List<? extends com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder> 
        getChunkOrBuilderList();
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder getChunkOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SegmentData}
   */
  public static final class SegmentData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SegmentData)
      SegmentDataOrBuilder {
    // Use SegmentData.newBuilder() to construct.
    private SegmentData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SegmentData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SegmentData defaultInstance;
    public static SegmentData getDefaultInstance() {
      return defaultInstance;
    }

    public SegmentData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SegmentData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              offset_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                chunk_ = new java.util.ArrayList<com.cloudata.blockstore.VolumeProto.ChunkData>();
                mutable_bitField0_ |= 0x00000002;
              }
              chunk_.add(input.readMessage(com.cloudata.blockstore.VolumeProto.ChunkData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          chunk_ = java.util.Collections.unmodifiableList(chunk_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.blockstore.VolumeProto.internal_static_SegmentData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.blockstore.VolumeProto.internal_static_SegmentData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.blockstore.VolumeProto.SegmentData.class, com.cloudata.blockstore.VolumeProto.SegmentData.Builder.class);
    }

    public static com.google.protobuf.Parser<SegmentData> PARSER =
        new com.google.protobuf.AbstractParser<SegmentData>() {
      public SegmentData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SegmentData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SegmentData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int CHUNK_FIELD_NUMBER = 2;
    private java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData> chunk_;
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    public java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData> getChunkList() {
      return chunk_;
    }
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    public java.util.List<? extends com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder> 
        getChunkOrBuilderList() {
      return chunk_;
    }
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    public int getChunkCount() {
      return chunk_.size();
    }
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    public com.cloudata.blockstore.VolumeProto.ChunkData getChunk(int index) {
      return chunk_.get(index);
    }
    /**
     * <code>repeated .ChunkData chunk = 2;</code>
     */
    public com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder getChunkOrBuilder(
        int index) {
      return chunk_.get(index);
    }

    private void initFields() {
      offset_ = 0L;
      chunk_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, offset_);
      }
      for (int i = 0; i < chunk_.size(); i++) {
        output.writeMessage(2, chunk_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, offset_);
      }
      for (int i = 0; i < chunk_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chunk_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.SegmentData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.blockstore.VolumeProto.SegmentData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SegmentData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SegmentData)
        com.cloudata.blockstore.VolumeProto.SegmentDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.blockstore.VolumeProto.internal_static_SegmentData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.blockstore.VolumeProto.internal_static_SegmentData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.blockstore.VolumeProto.SegmentData.class, com.cloudata.blockstore.VolumeProto.SegmentData.Builder.class);
      }

      // Construct using com.cloudata.blockstore.VolumeProto.SegmentData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChunkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chunkBuilder_ == null) {
          chunk_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          chunkBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.blockstore.VolumeProto.internal_static_SegmentData_descriptor;
      }

      public com.cloudata.blockstore.VolumeProto.SegmentData getDefaultInstanceForType() {
        return com.cloudata.blockstore.VolumeProto.SegmentData.getDefaultInstance();
      }

      public com.cloudata.blockstore.VolumeProto.SegmentData build() {
        com.cloudata.blockstore.VolumeProto.SegmentData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.blockstore.VolumeProto.SegmentData buildPartial() {
        com.cloudata.blockstore.VolumeProto.SegmentData result = new com.cloudata.blockstore.VolumeProto.SegmentData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.offset_ = offset_;
        if (chunkBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            chunk_ = java.util.Collections.unmodifiableList(chunk_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.chunk_ = chunk_;
        } else {
          result.chunk_ = chunkBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.blockstore.VolumeProto.SegmentData) {
          return mergeFrom((com.cloudata.blockstore.VolumeProto.SegmentData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.blockstore.VolumeProto.SegmentData other) {
        if (other == com.cloudata.blockstore.VolumeProto.SegmentData.getDefaultInstance()) return this;
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (chunkBuilder_ == null) {
          if (!other.chunk_.isEmpty()) {
            if (chunk_.isEmpty()) {
              chunk_ = other.chunk_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureChunkIsMutable();
              chunk_.addAll(other.chunk_);
            }
            onChanged();
          }
        } else {
          if (!other.chunk_.isEmpty()) {
            if (chunkBuilder_.isEmpty()) {
              chunkBuilder_.dispose();
              chunkBuilder_ = null;
              chunk_ = other.chunk_;
              bitField0_ = (bitField0_ & ~0x00000002);
              chunkBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChunkFieldBuilder() : null;
            } else {
              chunkBuilder_.addAllMessages(other.chunk_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.blockstore.VolumeProto.SegmentData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.blockstore.VolumeProto.SegmentData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long offset_ ;
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000001;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData> chunk_ =
        java.util.Collections.emptyList();
      private void ensureChunkIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          chunk_ = new java.util.ArrayList<com.cloudata.blockstore.VolumeProto.ChunkData>(chunk_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudata.blockstore.VolumeProto.ChunkData, com.cloudata.blockstore.VolumeProto.ChunkData.Builder, com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder> chunkBuilder_;

      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData> getChunkList() {
        if (chunkBuilder_ == null) {
          return java.util.Collections.unmodifiableList(chunk_);
        } else {
          return chunkBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public int getChunkCount() {
        if (chunkBuilder_ == null) {
          return chunk_.size();
        } else {
          return chunkBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public com.cloudata.blockstore.VolumeProto.ChunkData getChunk(int index) {
        if (chunkBuilder_ == null) {
          return chunk_.get(index);
        } else {
          return chunkBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder setChunk(
          int index, com.cloudata.blockstore.VolumeProto.ChunkData value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.set(index, value);
          onChanged();
        } else {
          chunkBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder setChunk(
          int index, com.cloudata.blockstore.VolumeProto.ChunkData.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.set(index, builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder addChunk(com.cloudata.blockstore.VolumeProto.ChunkData value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.add(value);
          onChanged();
        } else {
          chunkBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder addChunk(
          int index, com.cloudata.blockstore.VolumeProto.ChunkData value) {
        if (chunkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChunkIsMutable();
          chunk_.add(index, value);
          onChanged();
        } else {
          chunkBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder addChunk(
          com.cloudata.blockstore.VolumeProto.ChunkData.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.add(builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder addChunk(
          int index, com.cloudata.blockstore.VolumeProto.ChunkData.Builder builderForValue) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.add(index, builderForValue.build());
          onChanged();
        } else {
          chunkBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder addAllChunk(
          java.lang.Iterable<? extends com.cloudata.blockstore.VolumeProto.ChunkData> values) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, chunk_);
          onChanged();
        } else {
          chunkBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder clearChunk() {
        if (chunkBuilder_ == null) {
          chunk_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          chunkBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public Builder removeChunk(int index) {
        if (chunkBuilder_ == null) {
          ensureChunkIsMutable();
          chunk_.remove(index);
          onChanged();
        } else {
          chunkBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public com.cloudata.blockstore.VolumeProto.ChunkData.Builder getChunkBuilder(
          int index) {
        return getChunkFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder getChunkOrBuilder(
          int index) {
        if (chunkBuilder_ == null) {
          return chunk_.get(index);  } else {
          return chunkBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public java.util.List<? extends com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder> 
           getChunkOrBuilderList() {
        if (chunkBuilder_ != null) {
          return chunkBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(chunk_);
        }
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public com.cloudata.blockstore.VolumeProto.ChunkData.Builder addChunkBuilder() {
        return getChunkFieldBuilder().addBuilder(
            com.cloudata.blockstore.VolumeProto.ChunkData.getDefaultInstance());
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public com.cloudata.blockstore.VolumeProto.ChunkData.Builder addChunkBuilder(
          int index) {
        return getChunkFieldBuilder().addBuilder(
            index, com.cloudata.blockstore.VolumeProto.ChunkData.getDefaultInstance());
      }
      /**
       * <code>repeated .ChunkData chunk = 2;</code>
       */
      public java.util.List<com.cloudata.blockstore.VolumeProto.ChunkData.Builder> 
           getChunkBuilderList() {
        return getChunkFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudata.blockstore.VolumeProto.ChunkData, com.cloudata.blockstore.VolumeProto.ChunkData.Builder, com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder> 
          getChunkFieldBuilder() {
        if (chunkBuilder_ == null) {
          chunkBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cloudata.blockstore.VolumeProto.ChunkData, com.cloudata.blockstore.VolumeProto.ChunkData.Builder, com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder>(
                  chunk_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          chunk_ = null;
        }
        return chunkBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SegmentData)
    }

    static {
      defaultInstance = new SegmentData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SegmentData)
  }

  public interface ChunkDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 start = 1;</code>
     */
    boolean hasStart();
    /**
     * <code>optional uint32 start = 1;</code>
     */
    int getStart();

    /**
     * <code>optional uint32 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint32 length = 2;</code>
     */
    int getLength();

    /**
     * <code>optional bytes hash = 3;</code>
     */
    boolean hasHash();
    /**
     * <code>optional bytes hash = 3;</code>
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>optional uint32 skip = 4;</code>
     */
    boolean hasSkip();
    /**
     * <code>optional uint32 skip = 4;</code>
     */
    int getSkip();
  }
  /**
   * Protobuf type {@code ChunkData}
   */
  public static final class ChunkData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChunkData)
      ChunkDataOrBuilder {
    // Use ChunkData.newBuilder() to construct.
    private ChunkData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChunkData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChunkData defaultInstance;
    public static ChunkData getDefaultInstance() {
      return defaultInstance;
    }

    public ChunkData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              start_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              hash_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              skip_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudata.blockstore.VolumeProto.internal_static_ChunkData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudata.blockstore.VolumeProto.internal_static_ChunkData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudata.blockstore.VolumeProto.ChunkData.class, com.cloudata.blockstore.VolumeProto.ChunkData.Builder.class);
    }

    public static com.google.protobuf.Parser<ChunkData> PARSER =
        new com.google.protobuf.AbstractParser<ChunkData>() {
      public ChunkData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private int start_;
    /**
     * <code>optional uint32 start = 1;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 start = 1;</code>
     */
    public int getStart() {
      return start_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <code>optional uint32 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>optional bytes hash = 3;</code>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes hash = 3;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int SKIP_FIELD_NUMBER = 4;
    private int skip_;
    /**
     * <code>optional uint32 skip = 4;</code>
     */
    public boolean hasSkip() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 skip = 4;</code>
     */
    public int getSkip() {
      return skip_;
    }

    private void initFields() {
      start_ = 0;
      length_ = 0;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      skip_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, hash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, skip_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, start_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, hash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, skip_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudata.blockstore.VolumeProto.ChunkData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudata.blockstore.VolumeProto.ChunkData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkData)
        com.cloudata.blockstore.VolumeProto.ChunkDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudata.blockstore.VolumeProto.internal_static_ChunkData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudata.blockstore.VolumeProto.internal_static_ChunkData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudata.blockstore.VolumeProto.ChunkData.class, com.cloudata.blockstore.VolumeProto.ChunkData.Builder.class);
      }

      // Construct using com.cloudata.blockstore.VolumeProto.ChunkData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        start_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        skip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudata.blockstore.VolumeProto.internal_static_ChunkData_descriptor;
      }

      public com.cloudata.blockstore.VolumeProto.ChunkData getDefaultInstanceForType() {
        return com.cloudata.blockstore.VolumeProto.ChunkData.getDefaultInstance();
      }

      public com.cloudata.blockstore.VolumeProto.ChunkData build() {
        com.cloudata.blockstore.VolumeProto.ChunkData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudata.blockstore.VolumeProto.ChunkData buildPartial() {
        com.cloudata.blockstore.VolumeProto.ChunkData result = new com.cloudata.blockstore.VolumeProto.ChunkData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.skip_ = skip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudata.blockstore.VolumeProto.ChunkData) {
          return mergeFrom((com.cloudata.blockstore.VolumeProto.ChunkData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudata.blockstore.VolumeProto.ChunkData other) {
        if (other == com.cloudata.blockstore.VolumeProto.ChunkData.getDefaultInstance()) return this;
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasSkip()) {
          setSkip(other.getSkip());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudata.blockstore.VolumeProto.ChunkData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudata.blockstore.VolumeProto.ChunkData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int start_ ;
      /**
       * <code>optional uint32 start = 1;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 start = 1;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <code>optional uint32 start = 1;</code>
       */
      public Builder setStart(int value) {
        bitField0_ |= 0x00000001;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 start = 1;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>optional uint32 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>optional uint32 length = 2;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private int skip_ ;
      /**
       * <code>optional uint32 skip = 4;</code>
       */
      public boolean hasSkip() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 skip = 4;</code>
       */
      public int getSkip() {
        return skip_;
      }
      /**
       * <code>optional uint32 skip = 4;</code>
       */
      public Builder setSkip(int value) {
        bitField0_ |= 0x00000008;
        skip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 skip = 4;</code>
       */
      public Builder clearSkip() {
        bitField0_ = (bitField0_ & ~0x00000008);
        skip_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChunkData)
    }

    static {
      defaultInstance = new ChunkData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ChunkData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VolumeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VolumeData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SegmentData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SegmentData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChunkData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/VolumeProto.proto\"j\n\nVo" +
      "lumeData\022\025\n\rsegment_count\030\002 \001(\r\022\024\n\014segme" +
      "nt_size\030\003 \001(\r\022\030\n\020segment_store_id\030\004 \001(\014\022" +
      "\025\n\rblob_store_id\030\005 \001(\014\"8\n\013SegmentData\022\016\n" +
      "\006offset\030\001 \001(\004\022\031\n\005chunk\030\002 \003(\0132\n.ChunkData" +
      "\"F\n\tChunkData\022\r\n\005start\030\001 \001(\r\022\016\n\006length\030\002" +
      " \001(\r\022\014\n\004hash\030\003 \001(\014\022\014\n\004skip\030\004 \001(\rB\031\n\027com." +
      "cloudata.blockstore"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VolumeData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VolumeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VolumeData_descriptor,
        new java.lang.String[] { "SegmentCount", "SegmentSize", "SegmentStoreId", "BlobStoreId", });
    internal_static_SegmentData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SegmentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SegmentData_descriptor,
        new java.lang.String[] { "Offset", "Chunk", });
    internal_static_ChunkData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ChunkData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChunkData_descriptor,
        new java.lang.String[] { "Start", "Length", "Hash", "Skip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
